// <auto-generated />
using System;
using Company.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Company.Data.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20221221053629_SeedDataAdded")]
    partial class SeedDataAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Company.Data.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("OrganisationNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Namco",
                            OrganisationNumber = "89323212"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Alibaba",
                            OrganisationNumber = "42342342"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Samsung",
                            OrganisationNumber = "64363884"
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Tesla",
                            OrganisationNumber = "88999123"
                        });
                });

            modelBuilder.Entity("Company.Data.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            DepartmentName = "DEV"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            DepartmentName = "Buisness"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 2,
                            DepartmentName = "DEV"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 2,
                            DepartmentName = "Buisness"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 2,
                            DepartmentName = "HardWare"
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 3,
                            DepartmentName = "Buisness"
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 3,
                            DepartmentName = "DEV"
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 3,
                            DepartmentName = "HardWare"
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 4,
                            DepartmentName = "HardWare"
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = 4,
                            DepartmentName = "Buisness"
                        },
                        new
                        {
                            Id = 11,
                            CompanyId = 4,
                            DepartmentName = "DEV"
                        });
                });

            modelBuilder.Entity("Company.Data.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("Union")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            FirstName = "Katsuhiro",
                            LastName = "Harada",
                            Salary = 2500000m,
                            Union = true
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            FirstName = "Seiichi",
                            LastName = "Ishii",
                            Salary = 100000000m,
                            Union = true
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 11,
                            FirstName = "Elon",
                            LastName = "Musk",
                            Salary = 1000000000m,
                            Union = true
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 5,
                            FirstName = "Jack",
                            LastName = "Ma",
                            Salary = 100000000m,
                            Union = true
                        });
                });

            modelBuilder.Entity("Company.Data.Entities.EmployeePosition", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "PositionId");

                    b.HasIndex("PositionId");

                    b.ToTable("Employeeposition");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            PositionId = 1
                        },
                        new
                        {
                            EmployeeId = 1,
                            PositionId = 5
                        },
                        new
                        {
                            EmployeeId = 2,
                            PositionId = 2
                        },
                        new
                        {
                            EmployeeId = 2,
                            PositionId = 5
                        },
                        new
                        {
                            EmployeeId = 3,
                            PositionId = 1
                        },
                        new
                        {
                            EmployeeId = 3,
                            PositionId = 4
                        },
                        new
                        {
                            EmployeeId = 4,
                            PositionId = 1
                        },
                        new
                        {
                            EmployeeId = 4,
                            PositionId = 6
                        });
                });

            modelBuilder.Entity("Company.Data.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Position");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PositionName = "CEO"
                        },
                        new
                        {
                            Id = 2,
                            PositionName = "Game DEV"
                        },
                        new
                        {
                            Id = 3,
                            PositionName = "FrontDEV"
                        },
                        new
                        {
                            Id = 4,
                            PositionName = "BackDEV"
                        },
                        new
                        {
                            Id = 5,
                            PositionName = "FullstackDEV"
                        },
                        new
                        {
                            Id = 6,
                            PositionName = "BuisnessChief"
                        },
                        new
                        {
                            Id = 7,
                            PositionName = "UX Desginer"
                        });
                });

            modelBuilder.Entity("EmployeePosition", b =>
                {
                    b.Property<int>("EmployeesId")
                        .HasColumnType("int");

                    b.Property<int>("PositionsId")
                        .HasColumnType("int");

                    b.HasKey("EmployeesId", "PositionsId");

                    b.HasIndex("PositionsId");

                    b.ToTable("EmployeePosition");
                });

            modelBuilder.Entity("Company.Data.Entities.Company", b =>
                {
                    b.HasOne("Company.Data.Entities.Department", null)
                        .WithMany("Companies")
                        .HasForeignKey("DepartmentId");
                });

            modelBuilder.Entity("Company.Data.Entities.Department", b =>
                {
                    b.HasOne("Company.Data.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Company.Data.Entities.Employee", b =>
                {
                    b.HasOne("Company.Data.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Company.Data.Entities.EmployeePosition", b =>
                {
                    b.HasOne("Company.Data.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Company.Data.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("EmployeePosition", b =>
                {
                    b.HasOne("Company.Data.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Company.Data.Entities.Position", null)
                        .WithMany()
                        .HasForeignKey("PositionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Company.Data.Entities.Department", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
